import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const source=fs.readFileSync(new URL('../ESP32_WiFi_StandAlone_Test/WebPage.h',import.meta.url),'utf8');
const preview=fs.readFileSync(new URL('../preview/index.html',import.meta.url),'utf8');
const sourceScript=source.match(/<script>([\s\S]*?)<\/script>/)[1];
const scripts=[...preview.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
assert.equal(scripts.length,2);
assert.equal(scripts[1],sourceScript,'Preview must execute the exact source UI script.');
assert.match(preview,/ตัวอย่างจำลอง — ไม่เชื่อมต่อบอร์ด\/ไม่ใช่ผลทดสอบฮาร์ดแวร์/);
assert.equal(/<script[^>]+src=|<link[^>]+href=/i.test(preview),false,'Preview has no external script/style dependency.');
const elements=new Map();
const document={activeElement:null,addEventListener(){},getElementById(id){if(!elements.has(id))elements.set(id,{id,value:0,textContent:'',innerHTML:'',style:{},classList:{toggle(){}}});return elements.get(id);}};
const context=vm.createContext({document,Headers,TextEncoder,setInterval(){},setTimeout(){return 1;},clearTimeout(){}});
context.window=context;
for(const script of scripts)new vm.Script(script).runInContext(context);
await new Promise(resolve=>setImmediate(resolve));
assert.equal(await context.cmd('run',1),true);
assert.equal(document.getElementById('status').textContent,'RUNNING');
assert.equal(await context.cmd('rpm',2500),true);
assert.equal(document.getElementById('rpm').value,2500);
assert.equal(await context.cmd('tps',80),true);
assert.equal(document.getElementById('tps').value,80);
assert.equal(await context.cmd('profile',1),true);
assert.match(document.getElementById('profileInfo').innerHTML,/VR \/ Hall/);
assert.equal(await context.cmd('run',0),true);
assert.equal(document.getElementById('status').textContent,'STOPPED');
const before=await(await context.fetch('/api/state')).json();
const rejected=await context.fetch('/api/set',{method:'POST',headers:{'Content-Type':'text/plain'},body:'selftest=1&rpm=bad'});
assert.equal(rejected.status,400);
assert.deepEqual(await(await context.fetch('/api/state')).json(),before,'Mock demonstration rejects the whole mixed command.');
assert.equal(await context.cmd('rpm',9000),false);
assert.match(document.getElementById('commandError').textContent,/offline mock/);
assert.equal((await context.fetch('https://example.com')).status,404,'Unknown URLs never access the network.');
console.log('Offline preview tests passed: exact source UI extraction, local scripts, mock controls, error display, and no native-fetch fallback. These are not HTTP/board tests.');
